version: '3.3'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: annotation-backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    volumes:
      - annotation-platform-backend-volume:/app/data
    networks:
      - annotation-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: annotation-frontend
    ports:
      - "9999:80"
    depends_on:
      - backend
    networks:
      - annotation-network
    restart: unless-stopped

  # Optional: Redis for caching (if needed)
  # redis:
  #   image: redis:7-alpine
  #   container_name: annotation-redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - annotation-network
  #   restart: unless-stopped

networks:
  annotation-network:
    driver: bridge

volumes:
  annotation-platform-backend-volume:
    driver: local 